spring.application.name=optima-cms-adapter
# Omit JSON properties that are null (catalog models + nested maps)
spring.jackson.default-property-inclusion=non_null
spring.output.ansi.enabled=ALWAYS

# Server
server.port=9090
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.server.port=9091

# Authentication
keycloak.resource-server.enabled=true
keycloak.resource-server.required-role=ESB_AGENT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sso-staging.amdocsdigitalbss.cloud/auth/realms/selfcare-optima
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sso.dvint.corp.amdocs.com/auth/realms/selfcare-optima
keycloak.resource-server.truststore.location=classpath:ssl/truststore.jks
keycloak.resource-server.truststore.password=${KEYCLOAK_TRUSTSTORE_PASSWORD:aJAmCEKtvoA4Z4n83uET}
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=

# Camel
camel.springboot.name=${spring.application.name}
# camel.component.servlet.enabled=true

# Logging
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/cms-adapter.log
logging.logback.rollingpolicy.file-name-pattern=logs/cms-adapter-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.clean-history-on-start=false

# Magnolia

magnolia.base.url=http://localhost:8080/magnolia
magnolia.usr=superuser
magnolia.pass=superuser